# permissions for end users to view memcachedbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memcachedbackup-viewer-role
rules:
- apiGroups:
  - cache.my.domain
  resources:
  - memcachedbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.my.domain
  resources:
  - memcachedbackups/status
  verbs:
  - get
